mqserver:
  hostip: 127.0.0.1
  port: 1883
  topic: /senso-care/sensors/+
  username: artemis
  password: artemis
  qos: 0
database:
  connectionuri: http://localhost:8086
  username: influxdb
  password: influxdb
  dbname: sensocare
  retentionpolicy: one_month
cores: 6